site_name: yhwu_is's Teaching Notes
site_url: https://yhwu-is.github.io/Teach
site_author: yhwu_is

theme:
  name: material
  language: 'zh'
  palette:
    - scheme: default # 日间模式
      primary: indigo # 上方的
      accent: cyan # 链接等可交互元件的高亮色
      toggle:
        icon: material/weather-night # 图标
        name: 切换至夜间模式 # 鼠标悬浮提示
    - scheme: slate # 夜间模式
      primary: black 
      accent: cyan
      toggle:
        icon: material/weather-sunny
        name: 切换至日间模式
  features: 
    - content.code.annotate
    - navigation.footer
    - navigation.instant #- header.autohide  #自动隐藏
    #- announce.dismiss #呈现可标记为由用户读取的临时公告，可以包含一个用于取消当前公告的按钮
    - navigation.tracking #地址栏中的 URL 将自动更新为在目录中突出显示的活动锚点
    - navigation.tabs #顶级部分将呈现在上面视口标题下方的菜单层中，但在移动设备上保持原样
    #- navigation.tabs.sticky  #启用粘性选项卡后，导航选项卡将锁定在标题下方，并在向下滚动时始终保持可见
    #- navigation.sections #启用部分后，顶级部分在边栏中呈现为1220px以上视口的组，但在移动设备上保持原样
    - navigation.top # 返回顶部的按钮 在上滑时出现
    - search.suggest # 搜索输入一些字母时推荐补全整个单词
    - search.highlight # 搜索出的文章关键词加入高亮
    #- navigation.expand # 打开Tab时左侧目录全部展开
    - navigation.indexes #启用节索引页后，可以将文档直接附加到节
    - search.share #搜索分享按钮
  icon: 
    repo: fontawesome/brands/github #右上角图标
  font: false

edit_uri: edit/main/docs # 编辑按钮跳转的链接 
repo_url: https://github.com/yhwu-is/Notes # 右上角点击跳转的链接
repo_name: GitHub仓库 # 右上角的名字
nav: 
  - Welcome: index.md
  - 数学: 
    - 线性代数: 
      - 简介: math/linear_algebra/index.md
  - 理论计算机基础:
    - 高级数据结构与算法分析: 
      - 引言与基础知识: tcs/dsa/dsa0.md
    - 编程语言原理:
      - lambda表达式: tcs/pfpl/lambda.md
      - 判断与规则: tcs/pfpl/P1.md
      - 静态与动态: tcs/pfpl/P2.md
      - 全函数: tcs/pfpl/P3.md
      - 有限数据类型: tcs/pfpl/P4.md
      - 无限数据类型: tcs/pfpl/P6.md
  - 计算与经济:
    - 数据要素市场:
      - 课程简介与绪论: ec/data_market/intro.md

copyright: Copyright &copy; 2023-2024 吴一航

extra:
  generator: false  #删除页脚显示“使用 MkDocs 材料制造”
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/yhwu-is
    - icon: fontawesome/solid/paper-plane
      link: mailto:<yhwu_is@zju.edu.cn> #联系方式

plugins:
  - search
  - tags  #标签

markdown_extensions:
  - toc:
      permalink: true
      toc_depth: 4
  - meta
  - def_list
  - attr_list
  - md_in_html
  - sane_lists
  - admonition
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.snippets
  - pymdownx.magiclink
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.tabbed:
      alternate_style: true 
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/extra.js
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js